config/routes.rb
Rails.application.routes.draw do
  resources :statements, only: [:index, :new, :create, :destroy]
  root "statements#index"

end

app/models/statement.rb
class Statement < ActiveRecord::Base
  has_attached_file :attachment,
                    default_url: 'https://s3.amazonaws.com/www.premedinc.com/statements/missing.png',
                    storage: :s3,
                    bucket: Rails.env.production? ? 'www.premedinc.com' : 'www.premedinc.com.dev'
  do_not_validate_attachment_file_type :attachment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  def index
    @statements = Statement.all
  end

  def new
    @statement = Statement.new
    @statement.attachment
  end

  def create
    @statement = Statement.new(statement_params)

    if @statement.save
      redirect_to statements_path, notice: "The statement #{@statement.attachment.url} has been uploaded."
    else
      render "new"
    end
  end

  def destroy
    @statement = Statement.find(params[:id])
    @statement.destroy
    redirect_to statements_path, notice: "The statement #{@statement.attachment.url} has been removed."
  end

  private
    def statement_params
      params.require(:statement).permit(:attachment)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Statements</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class = "container" style = "padding-top:20px;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/statements/_form.html.erb
<%= form_for(@statement) do |f| %>
    <% if @statement.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
          </button>
          <h2><%= pluralize(@statement.errors.count, "error") %> prohibited this statement from being saved:</h2>

          <ul>
            <% @statement.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="well">
          <%= f.file_field :attachment %>
          <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/statements/index.html.erb
<% if !flash[:notice].blank? %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
<% end %>

<br/>

<%= link_to "New Statement", new_statement_path, class: "btn btn-primary" %>
<br/>
<br/>

<table class="table table-bordered table-striped">
  <thead>.
  <tr>
    <th>Name</th>
    <th>Download Link</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @statements.each do |s| %>
      <tr>
        <td><%= s.attachment_file_name %></td>
        <td><%= link_to "Download Statement", s.attachment.url %></td>
        <td><%= button_to "Delete", s, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete
          #{s.attachment.url}?" %>
        </td>
      </tr>

  <% end %>
  </tbody>

</table>

app/views/statements/new.html.erb
<h1>New Statement</h1>

<%= render 'form' %>

<%= link_to 'Back', statements_path %>